// @generated
// This file is @generated by prost-build.
/// Value covers the full internal type system. All pipeline data must map to one of these.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Value {
    #[prost(oneof="value::Kind", tags="1, 2, 3, 4, 5, 6, 7")]
    pub kind: ::core::option::Option<value::Kind>,
}
/// Nested message and enum types in `Value`.
pub mod value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(string, tag="1")]
        StringValue(::prost::alloc::string::String),
        #[prost(bytes, tag="2")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
        #[prost(int64, tag="3")]
        IntValue(i64),
        #[prost(double, tag="4")]
        FloatValue(f64),
        #[prost(bool, tag="5")]
        BoolValue(bool),
        #[prost(message, tag="6")]
        SliceValue(super::Slice),
        #[prost(message, tag="7")]
        MapValue(super::Map),
    }
}
/// Slice is a homogeneous ordered list. Element type is by convention, not enforced here.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Slice {
    #[prost(message, repeated, tag="1")]
    pub values: ::prost::alloc::vec::Vec<Value>,
}
/// Map is a string-keyed dictionary of Values.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Map {
    #[prost(map="string, message", tag="1")]
    pub values: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Source {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(map="string, message", tag="2")]
    pub attributes: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(message, optional, tag="1")]
    pub source: ::core::option::Option<Source>,
    /// Arrow IPC stream: one RecordBatch (schema + columnar buffers)
    #[prost(bytes="vec", tag="2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="3")]
    pub received_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Batch is the unit passed to every Exporter on each flush.
/// Multiple events from the same Source are not merged; they appear as separate entries.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Batch {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<Event>,
}
/// IngestRequest is what a client sends to the HTTP receiver.
/// Rows are column:value pairs; the receiver normalizes to an Arrow RecordBatch internally.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestRequest {
    #[prost(string, tag="1")]
    pub datasource_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub ingestion_key: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub rows: ::prost::alloc::vec::Vec<Row>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Row {
    #[prost(map="string, message", tag="1")]
    pub fields: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IngestResponse {
    #[prost(bool, tag="1")]
    pub accepted: bool,
    /// populated on rejection; empty on success
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
