pub mod components;
pub mod config;
pub mod engine;
pub mod error;
pub mod executor;
pub mod exporter;
pub mod pipeline;
pub mod processor;
pub mod receiver;
pub mod registry;
pub mod types;

/// Generated protobuf types. The file is pre-generated by buf and included directly
/// so no build.rs proto compilation step is required at development time.
pub mod proto {
    pub mod common {
        pub mod v1 {
            include!("proto/common/v1/common.v1.rs");
        }
    }
}

// Component identity and factory surface — everything a component author needs.
pub use components::{Component, ComponentID, ComponentType, Settings};
pub use exporter::ExporterFactory;
pub use processor::ProcessorFactory;
pub use receiver::ReceiverFactory;

// Framework surface re-exports — everything a pipeline author needs.
pub use config::Config;
pub use engine::Engine;
pub use error::{IngestionError, Result};
pub use exporter::Exporter;
pub use pipeline::{ExporterGroup, Pipeline};
pub use processor::Processor;
pub use receiver::{Receiver, ReceiverHost};
pub use registry::ComponentRegistry;
pub use types::{Batch, Event, Source, Value};
